"""CWC epistemic safety primitives."""

from cwc.epistemics.lattice import (
    CapabilityBindingError,
    CapabilityType,
    EpistemicCapability,
    EpistemicError,
    EpistemicMachine,
    EpistemicRecord,
    EpistemicState,
    EvidenceClassError,
    EvidenceKind,
    EvidenceRef,
    EvidenceSource,
    IllegalTransition,
    POSITIVE_CHAIN,
    TERMINAL_STATES,
    positive_state_dominates,
)

from cwc.epistemics.self_falsification import (
    FalsificationAttack,
    FalsificationBindingError,
    FalsificationOutcome,
    FalsificationUpdate,
    SelfFalsificationDecision,
    SelfFalsificationError,
    SelfFalsificationState,
    apply_self_falsification_outcome,
    select_self_falsification_attack,
    verify_self_falsification_decision,
)

__all__ = [
    "CapabilityBindingError",
    "CapabilityType",
    "EpistemicCapability",
    "EpistemicError",
    "EpistemicMachine",
    "EpistemicRecord",
    "EpistemicState",
    "EvidenceClassError",
    "EvidenceKind",
    "EvidenceRef",
    "EvidenceSource",
    "IllegalTransition",
    "POSITIVE_CHAIN",
    "TERMINAL_STATES",
    "positive_state_dominates",
    "FalsificationAttack",
    "FalsificationBindingError",
    "FalsificationOutcome",
    "FalsificationUpdate",
    "SelfFalsificationDecision",
    "SelfFalsificationError",
    "SelfFalsificationState",
    "apply_self_falsification_outcome",
    "select_self_falsification_attack",
    "verify_self_falsification_decision",
]
