from __future__ import annotations

from cwc.governance.p19_verification_check_receipt import REQUIRED_CHECKS

CHECK_METHOD_IDS: dict[str, str] = {
    "REPOSITORY_IDENTITY": "DGC_P19_EXTERNAL_REPOSITORY_IDENTITY_V1",
    "THEOREM_AND_PLAN_IDENTITY": "DGC_P19_EXTERNAL_THEOREM_AND_PLAN_IDENTITY_V1",
    "SUBJECT_ROOT_REHASH": "DGC_P19_EXTERNAL_SUBJECT_ROOT_REHASH_V1",
    "P19_SEAL_REBUILD": "DGC_P19_EXTERNAL_P19_SEAL_REBUILD_V1",
    "PRIMARY_P9_RAW_REPLAY": "DGC_P19_EXTERNAL_PRIMARY_P9_RAW_REPLAY_V1",
    "GENERALIZATION_G1_G5_RAW_REPLAY": "DGC_P19_EXTERNAL_GENERALIZATION_G1_G5_RAW_REPLAY_V1",
    "FAULT_TOLERANCE_RAW_REPLAY": "DGC_P19_EXTERNAL_FAULT_TOLERANCE_RAW_REPLAY_V1",
    "INDEPENDENT_REPLICATION_RAW_REPLAY": "DGC_P19_EXTERNAL_INDEPENDENT_REPLICATION_RAW_REPLAY_V1",
}

if set(CHECK_METHOD_IDS) != REQUIRED_CHECKS:
    raise RuntimeError("P19 external verification method map differs from required check population")
if len(set(CHECK_METHOD_IDS.values())) != len(REQUIRED_CHECKS):
    raise RuntimeError("P19 external verification method identities must be unique")
